[theme]
base="light"
primaryColor="#EF8429"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8FAFC"
textColor="#172033"
font="sans serif"

[client]
toolbarMode="minimal"

[browser]
gatherUsageStats=false
